.phony all:
all:
	gcc -Wall diskhelp.c diskinfo.c -o diskinfo
	gcc -Wall diskhelp.c disklist.c -o disklist
	gcc -Wall diskhelp.c diskput.c -o diskput
	gcc -Wall diskhelp.c diskget.c -o diskget


.phony clean:
clean:
	-rm diskinfo
	-rm disklist
	-rm diskput
	-rm diskget
